import { Body, Controller, Delete, Get, Param, Patch, Post, Query, Req, UseGuards } from '@nestjs/common';
import { Roles } from 'src/auth/decorators/roles.decorator';
import type { AuthenticatedRequest } from 'src/auth/guards/jwt-auth.guard';
import { JwtAuthGuard } from 'src/auth/guards/jwt-auth.guard';
import { RolesGuard } from 'src/auth/guards/roles.guard';
import { UserRole } from 'src/common/enums/user-role.enum';
import { AutoGenerationConfirmDto } from './dto/auto-generation-confirm.dto';
import { AutoGenerationPreviewDto } from './dto/auto-generation-preview.dto';
import { CreateScheduleDTO } from './dto/create-schedule.dto';
import { UpdateScheduleDto } from './dto/update-schedule.dto';
import { SchedulesService } from './schedules.service';

@Controller('schedules')
@UseGuards(JwtAuthGuard, RolesGuard)
export class SchedulesController {
  constructor(
    private readonly schedulesService: SchedulesService
  ) {}

  @Get()
  async getAllSchedules(@Query() query: any) {
    return await this.schedulesService.getAllSchedules(query);
  }

  @Get('my-assignments')
  async getMyAssignments(@Req() request: AuthenticatedRequest) {
    return await this.schedulesService.getMyAssignments(request.user.sub);
  }

  @Post('sync-statuses')
  @Roles(UserRole.Admin)
  async syncPastScheduleStatuses() {
    return await this.schedulesService.syncPastScheduleStatuses();
  }

  @Post('auto-generation/preview')
  @Roles(UserRole.Admin)
  async previewAutoGeneratedSchedules(@Body() dto: AutoGenerationPreviewDto) {
    return await this.schedulesService.previewAutoGeneratedSchedules(dto);
  }

  @Post('auto-generation/confirm')
  @Roles(UserRole.Admin)
  async confirmAutoGeneratedSchedules(@Body() dto: AutoGenerationConfirmDto) {
    return await this.schedulesService.confirmAutoGeneratedSchedules(dto);
  }

  @Get(':id')
  async getScheduleById(@Param('id') id: string) {
    return await this.schedulesService.getScheduleById(id);
  }

  @Post()
  @Roles(UserRole.Admin)
  async createSchedule(@Body() dto: CreateScheduleDTO) {
    return await this.schedulesService.createSchedule(dto);
  }

  @Patch(':id')
  @Roles(UserRole.Admin)
  async updateScheduleById(
    @Param('id') id: string,
    @Body() dto: UpdateScheduleDto,
  ) {
    return await this.schedulesService.updateScheduleById(id, dto);
  }

  @Delete(':id')
  @Roles(UserRole.Admin)
  async deleteScheduleById(@Param('id') id: string) {
    return await this.schedulesService.deleteScheduleById(id);
  }
}
