import { BadRequestException, Injectable } from '@nestjs/common';
import { WorkerRole } from 'src/common/enums/worker-role.enum';
import { WorkerStatus } from 'src/common/enums/worker-status.enum';
import {
  RecurrenceType,
  WorkerEligibilityMode,
} from 'src/service-types/service-type.constants';
import { ServiceTypesService } from 'src/service-types/service-types.service';
import { WorkersService } from 'src/workers/workers.service';
import { AutoGenerationPreviewDto } from './dto/auto-generation-preview.dto';
import { SchedulesRepository } from './repositories/schedules.repository';
import { WorkerUnavailabilityService } from 'src/worker-unavailability/worker-unavailability.service';

type PreviewStatus = 'generated' | 'skipped' | 'needs_attention';

interface WorkerCandidate {
  _id: unknown;
  name: string;
  roles: WorkerRole[];
  status: WorkerStatus;
  worker_group_ids?: string[];
}

interface ScheduleLike {
  date: Date | string;
  service_type?: string;
  assignments?: Array<{ worker_id?: unknown }>;
}

interface FairnessScore {
  count: number;
  lastAssignedTime: number;
}

interface EligibilityRule {
  mode: WorkerEligibilityMode;
  allowed_group_ids: unknown[];
  preferred_group_ids: unknown[];
}

interface AssignmentSlotRule {
  key: string;
  label: string;
  allowed_roles: WorkerRole[];
  required: boolean;
  display_order: number;
  worker_eligibility_override?: EligibilityRule;
}

export interface AutoGeneratedAssignment {
  slot_key: string;
  role: WorkerRole;
  worker_id: string;
  worker_name: string;
}

export interface AutoGenerationPreviewRow {
  date: string;
  service_type: string;
  status: PreviewStatus;
  assignments: AutoGeneratedAssignment[];
  warnings: string[];
}

@Injectable()
export class ScheduleAutoGenerationService {
  constructor(
    private readonly schedulesRepository: SchedulesRepository,
    private readonly workersService: WorkersService,
    private readonly serviceTypesService: ServiceTypesService,
    private readonly workerUnavailabilityService: WorkerUnavailabilityService,
  ) {}

  async preview(dto: AutoGenerationPreviewDto) {
    const requestedServiceTypes = dto.service_types?.length
      ? [...new Set(dto.service_types)]
      : [dto.service_type ?? 'main'];
    const serviceTypes = await Promise.all(
      requestedServiceTypes.map((code) =>
        this.serviceTypesService.getByCode(code, true),
      ),
    );

    serviceTypes.forEach((serviceType) => {
      if (
        !serviceType.auto_generation_enabled ||
        serviceType.recurrence.type !== RecurrenceType.Weekly ||
        serviceType.recurrence.weekday === undefined
      ) {
        throw new BadRequestException(
          `${serviceType.name} is not available for monthly auto-generation`,
        );
      }
    });

    const includeOptionalRoles = dto.includeOptionalRoles ?? true;
    const monthStart = new Date(Date.UTC(dto.year, dto.month - 1, 1));
    const nextMonthStart = new Date(Date.UTC(dto.year, dto.month, 1));
    const previousMonthStart = new Date(Date.UTC(dto.year, dto.month - 2, 1));

    const [activeWorkersResult, monthSchedules, unavailableWorkerIdsByDate] =
      await Promise.all([
        this.workersService.getWorkers(WorkerStatus.Active),
        this.schedulesRepository.findSchedulesInDateRange(
          monthStart,
          nextMonthStart,
        ),
        this.workerUnavailabilityService.getUnavailableWorkerIds(
          monthStart,
          nextMonthStart,
        ),
      ]);
    const recentSchedulesByServiceType = new Map(
      await Promise.all(
        serviceTypes.map(async (serviceType) => [
          serviceType.code,
          await this.schedulesRepository.findSchedulesInDateRange(
            previousMonthStart,
            nextMonthStart,
            serviceType.code,
          ),
        ] as const),
      ),
    );

    const activeWorkers = await Promise.all(
      (activeWorkersResult.items as unknown as WorkerCandidate[]).map(
        async (worker) => ({
          ...worker,
          worker_group_ids: await this.workersService.getWorkerGroupIds(worker),
        }),
      ),
    );
    const monthSchedulesByDate = this.groupSchedulesByDate(
      monthSchedules as ScheduleLike[],
    );
    const reservedWorkerIdsByDate = new Map<string, Set<string>>();
    const workerPools = new Map(
      (dto.worker_pools ?? []).map((pool) => [
        `${pool.service_type}:${pool.slot_key}`,
        new Set(pool.worker_ids),
      ]),
    );
    const rows: AutoGenerationPreviewRow[] = [];

    serviceTypes.forEach((serviceType) => {
      const fairnessScores = this.buildFairnessScores(
        activeWorkers,
        (recentSchedulesByServiceType.get(serviceType.code) ?? []) as ScheduleLike[],
      );
      const slots = [...serviceType.assignment_slots]
        .sort((a, b) => a.display_order - b.display_order)
        .filter((slot) => slot.required || includeOptionalRoles);

      this.getDatesInMonth(
        dto.year,
        dto.month,
        serviceType.recurrence.weekday!,
      ).forEach((date) => {
        const dateKey = this.toDateKey(date);
        const schedulesOnDate = monthSchedulesByDate.get(dateKey) ?? [];
        const existingServiceSchedule = schedulesOnDate.find((schedule) => {
          return schedule.service_type === serviceType.code;
        });

        if (existingServiceSchedule) {
          rows.push({
            date: dateKey,
            service_type: serviceType.code,
            status: 'skipped',
            assignments: [],
            warnings: [
              `A ${serviceType.name} schedule already exists for this date.`,
            ],
          });
          return;
        }

        const usedWorkerIds = this.getAssignedWorkerIds(schedulesOnDate);
        reservedWorkerIdsByDate.get(dateKey)?.forEach((workerId) => {
          usedWorkerIds.add(workerId);
        });
        unavailableWorkerIdsByDate.get(dateKey)?.forEach((workerId) => {
          usedWorkerIds.add(workerId);
        });
        const assignments: AutoGeneratedAssignment[] = [];
        const warnings: string[] = [];

        slots.forEach((slot) => {
          const selected = this.selectWorkerForSlot(
            slot as AssignmentSlotRule,
            serviceType.worker_eligibility as EligibilityRule,
            activeWorkers,
            usedWorkerIds,
            fairnessScores,
            dto.allowYouthBackupFallback ?? true,
            serviceType.code,
            workerPools.get(`${serviceType.code}:${slot.key}`),
          );

          if (!selected) {
            if (slot.required) {
              warnings.push(`Missing required assignment: ${slot.label}`);
            }
            return;
          }

          const workerId = this.toId(selected.worker._id);
          usedWorkerIds.add(workerId);
          assignments.push({
            slot_key: slot.key,
            role: selected.role,
            worker_id: workerId,
            worker_name: selected.worker.name,
          });
          this.incrementFairnessScore(fairnessScores, workerId, date);
        });

        const reservedWorkerIds = reservedWorkerIdsByDate.get(dateKey) ?? new Set();
        assignments.forEach((assignment) => {
          reservedWorkerIds.add(assignment.worker_id);
        });
        reservedWorkerIdsByDate.set(dateKey, reservedWorkerIds);
        rows.push({
          date: dateKey,
          service_type: serviceType.code,
          status: warnings.length ? 'needs_attention' : 'generated',
          assignments,
          warnings,
        });
      });
    });

    return {
      year: dto.year,
      month: dto.month,
      service_type: serviceTypes[0].code,
      service_types: serviceTypes.map((serviceType) => serviceType.code),
      rows,
    };
  }

  async isGenerationDate(serviceTypeCode: string, date: Date) {
    const serviceType = await this.serviceTypesService.getByCode(
      serviceTypeCode,
      true,
    );

    return (
      serviceType.auto_generation_enabled &&
      serviceType.recurrence.type === RecurrenceType.Weekly &&
      date.getUTCDay() === serviceType.recurrence.weekday
    );
  }

  private selectWorkerForSlot(
    slot: AssignmentSlotRule,
    serviceEligibility: EligibilityRule,
    workers: WorkerCandidate[],
    usedWorkerIds: Set<string>,
    fairnessScores: Map<string, FairnessScore>,
    allowConfiguredFallback: boolean,
    serviceTypeCode: string,
    allowedWorkerIds?: Set<string>,
  ) {
    let eligibility = slot.worker_eligibility_override ?? serviceEligibility;

    if (
      serviceTypeCode === 'main' &&
      slot.key === 'backup' &&
      !allowConfiguredFallback &&
      eligibility.preferred_group_ids?.length
    ) {
      eligibility = {
        ...eligibility,
        allowed_group_ids: eligibility.preferred_group_ids,
      };
    }

    const candidates = workers.filter((worker) => {
      return (
        worker.status === WorkerStatus.Active &&
        (!allowedWorkerIds || allowedWorkerIds.has(this.toId(worker._id))) &&
        slot.allowed_roles.some((role) => worker.roles?.includes(role)) &&
        !usedWorkerIds.has(this.toId(worker._id)) &&
        this.isWorkerEligible(worker, eligibility)
      );
    });

    const preferredIds = new Set(
      (eligibility.preferred_group_ids ?? []).map(String),
    );
    const preferredCandidates = preferredIds.size
      ? candidates.filter((worker) =>
          worker.worker_group_ids?.some((id) => preferredIds.has(String(id))),
        )
      : [];
    const worker = this.pickFairestWorker(
      preferredCandidates.length ? preferredCandidates : candidates,
      fairnessScores,
    );

    if (!worker) {
      return undefined;
    }

    return {
      worker,
      role: slot.allowed_roles.find((role) => worker.roles.includes(role))!,
    };
  }

  private isWorkerEligible(
    worker: WorkerCandidate,
    eligibility: EligibilityRule,
  ) {
    if (eligibility.mode === WorkerEligibilityMode.Any) {
      return true;
    }

    const allowedIds = new Set(
      (eligibility.allowed_group_ids ?? []).map(String),
    );

    return worker.worker_group_ids?.some((id) => allowedIds.has(String(id)));
  }

  private pickFairestWorker(
    candidates: WorkerCandidate[],
    fairnessScores: Map<string, FairnessScore>,
  ) {
    return [...candidates].sort((a, b) => {
      const aScore = fairnessScores.get(this.toId(a._id)) ?? {
        count: 0,
        lastAssignedTime: 0,
      };
      const bScore = fairnessScores.get(this.toId(b._id)) ?? {
        count: 0,
        lastAssignedTime: 0,
      };

      if (aScore.count !== bScore.count) {
        return aScore.count - bScore.count;
      }

      if (aScore.lastAssignedTime !== bScore.lastAssignedTime) {
        return aScore.lastAssignedTime - bScore.lastAssignedTime;
      }

      return a.name.localeCompare(b.name);
    })[0];
  }

  private buildFairnessScores(
    workers: WorkerCandidate[],
    recentServiceSchedules: ScheduleLike[],
  ) {
    const scores = new Map<string, FairnessScore>();

    workers.forEach((worker) => {
      scores.set(this.toId(worker._id), { count: 0, lastAssignedTime: 0 });
    });

    recentServiceSchedules.forEach((schedule) => {
      const assignedTime = this.toDate(schedule.date).getTime();
      schedule.assignments?.forEach((assignment) => {
        if (!assignment.worker_id) {
          return;
        }

        const workerId = this.toId(assignment.worker_id);
        const score = scores.get(workerId) ?? {
          count: 0,
          lastAssignedTime: 0,
        };
        scores.set(workerId, {
          count: score.count + 1,
          lastAssignedTime: Math.max(score.lastAssignedTime, assignedTime),
        });
      });
    });

    return scores;
  }

  private incrementFairnessScore(
    scores: Map<string, FairnessScore>,
    workerId: string,
    date: Date,
  ) {
    const score = scores.get(workerId) ?? {
      count: 0,
      lastAssignedTime: 0,
    };
    scores.set(workerId, {
      count: score.count + 1,
      lastAssignedTime: Math.max(score.lastAssignedTime, date.getTime()),
    });
  }

  private getAssignedWorkerIds(schedules: ScheduleLike[]) {
    const workerIds = new Set<string>();
    schedules.forEach((schedule) => {
      schedule.assignments?.forEach((assignment) => {
        if (assignment.worker_id) {
          workerIds.add(this.toId(assignment.worker_id));
        }
      });
    });
    return workerIds;
  }

  private groupSchedulesByDate(schedules: ScheduleLike[]) {
    return schedules.reduce<Map<string, ScheduleLike[]>>((acc, schedule) => {
      const dateKey = this.toDateKey(schedule.date);
      const schedulesOnDate = acc.get(dateKey) ?? [];
      schedulesOnDate.push(schedule);
      acc.set(dateKey, schedulesOnDate);
      return acc;
    }, new Map());
  }

  private getDatesInMonth(year: number, month: number, weekday: number) {
    const dates: Date[] = [];
    const current = new Date(Date.UTC(year, month - 1, 1));

    while (current.getUTCMonth() === month - 1) {
      if (current.getUTCDay() === weekday) {
        dates.push(new Date(current));
      }
      current.setUTCDate(current.getUTCDate() + 1);
    }

    return dates;
  }

  private toDate(value: Date | string) {
    return value instanceof Date ? value : new Date(value);
  }

  private toDateKey(value: Date | string) {
    return this.toDate(value).toISOString().slice(0, 10);
  }

  private toId(value: unknown) {
    return typeof value === 'string' ? value : String(value);
  }
}
