import {
  BadRequestException,
  ForbiddenException,
  Injectable,
  NotFoundException,
} from '@nestjs/common';
import { Cron } from '@nestjs/schedule';
import { Types } from 'mongoose';
import { ScheduleStatus } from 'src/common/enums/schedule-status.enum';
import { UserRole } from 'src/common/enums/user-role.enum';
import { WorkerRole } from 'src/common/enums/worker-role.enum';
import { WorkerStatus } from 'src/common/enums/worker-status.enum';
import { WorkersService } from 'src/workers/workers.service';
import { AutoGenerationConfirmDto } from './dto/auto-generation-confirm.dto';
import { AutoGenerationPreviewDto } from './dto/auto-generation-preview.dto';
import { CreateScheduleDTO } from './dto/create-schedule.dto';
import { ScheduleAssignmentDto } from './dto/schedule-assignment.dto';
import { UpdateScheduleDto } from './dto/update-schedule.dto';
import { ScheduleAutoGenerationService } from './schedule-auto-generation.service';
import { SchedulesRepository } from './repositories/schedules.repository';
import { ServiceTypesService } from 'src/service-types/service-types.service';
import { WorkerEligibilityMode } from 'src/service-types/service-type.constants';

@Injectable()
export class SchedulesService {
  constructor(
    private readonly schedulesRepository: SchedulesRepository,
    private readonly workersService: WorkersService,
    private readonly scheduleAutoGenerationService: ScheduleAutoGenerationService,
    private readonly serviceTypesService: ServiceTypesService,
  ) {}

  async getAllSchedules(query: any = {}) {
    const filter: any = {};

    if (query.status) {
      filter.status = query.status;
    }

    if (query.service_type) {
      filter.service_type = query.service_type;
    }

    return await this.schedulesRepository.getRecords(filter, 1, 100, 'asc', 'date');
  }

  async getMyAssignments(userId: string) {
    const worker = await this.workersService.findWorkerByUserId(userId);

    if (!worker) {
      return { worker: null, items: [] };
    }

    const items = await this.schedulesRepository.findWorkerAssignments(
      worker._id.toString(),
      this.getCurrentLocalDate(),
    );

    return {
      worker: {
        _id: worker._id,
        name: worker.name,
        roles: worker.roles,
        leader_songs: await this.workersService.getLegacyLeaderSongsForWorker(
          worker._id.toString(),
        ),
      },
      items,
    };
  }

  async getScheduleById(id: string) {
    const schedule = await this.schedulesRepository.getRecordById(id);

    if (!schedule) {
      throw new NotFoundException('Schedule not found');
    }

    return schedule;
  }

  async createSchedule(dto: CreateScheduleDTO) {
    const date = this.normalizeScheduleDate(dto.date);
    const serviceType = await this.serviceTypesService.getByCode(
      dto.service_type || 'main',
      true,
    );
    this.validateRecurrenceDate(date, serviceType);
    const existingSchedule = await this.schedulesRepository.findScheduleOnDate(
      date,
      serviceType.code,
    );

    if (existingSchedule) {
      throw new BadRequestException(
        `A ${serviceType.name} schedule already exists for this date`,
      );
    }
    const assignments = await this.validateAndBuildAssignments(
      dto.assignments,
      date,
      serviceType,
    );

    return await this.schedulesRepository.insertRecord({
      date,
      service_type: serviceType.code,
      status: dto.status || this.getStatusForDate(date),
      assignments,
      songs: dto.songs || [],
      lineup: dto.lineup,
      notes: dto.notes,
    } as any);
  }

  async previewAutoGeneratedSchedules(dto: AutoGenerationPreviewDto) {
    return await this.scheduleAutoGenerationService.preview(dto);
  }

  async confirmAutoGeneratedSchedules(dto: AutoGenerationConfirmDto) {
    const seenDates = new Set<string>();
    const seenWorkerIdsByDate = new Map<string, Set<string>>();
    const preparedSchedules: any[] = [];

    for (const schedule of dto.schedules) {
      const date = this.normalizeScheduleDate(schedule.date);
      const dateKey = date.toISOString().slice(0, 10);
      const serviceTypeCode = schedule.service_type || 'main';
      const serviceType = await this.serviceTypesService.getByCode(
        serviceTypeCode,
        true,
      );
      const scheduleKey = `${dateKey}:${serviceType.code}`;

      if (!(await this.scheduleAutoGenerationService.isGenerationDate(serviceType.code, date))) {
        throw new BadRequestException(
          `${dateKey} is not a valid auto-generation date for ${serviceType.name}`,
        );
      }

      if (seenDates.has(scheduleKey)) {
        throw new BadRequestException(
          `Duplicate generated ${serviceType.name} schedule date: ${dateKey}`,
        );
      }

      seenDates.add(scheduleKey);

      const existingSchedule = await this.schedulesRepository.findScheduleOnDate(
        date,
        serviceType.code,
      );

      if (existingSchedule) {
        throw new BadRequestException(
          `A ${serviceType.name} schedule already exists for ${dateKey}`,
        );
      }

      const assignments = await this.validateAndBuildAssignments(
        schedule.assignments,
        date,
        serviceType,
      );
      const seenWorkerIds = seenWorkerIdsByDate.get(dateKey) ?? new Set<string>();
      const conflictingWorker = assignments.find((assignment) => {
        return seenWorkerIds.has(assignment.worker_id.toString());
      });

      if (conflictingWorker) {
        throw new BadRequestException(
          'A worker is already assigned to another generated schedule on this date',
        );
      }

      assignments.forEach((assignment) => {
        seenWorkerIds.add(assignment.worker_id.toString());
      });
      seenWorkerIdsByDate.set(dateKey, seenWorkerIds);

      preparedSchedules.push({
        date,
        service_type: serviceType.code,
        status: this.getStatusForDate(date),
        assignments,
        songs: schedule.songs || [],
        lineup: schedule.lineup,
        notes: schedule.notes,
      });
    }

    const createdSchedules: any[] = [];

    for (const schedule of preparedSchedules) {
      createdSchedules.push(
        await this.schedulesRepository.insertRecord(schedule as any),
      );
    }

    return createdSchedules;
  }

  async updateScheduleById(id: string, dto: UpdateScheduleDto) {
    const existing = await this.getScheduleById(id);
    const date = dto.date ? this.normalizeScheduleDate(dto.date) : existing.date;
    const serviceType = await this.serviceTypesService.getByCode(
      dto.service_type || existing.service_type || 'main',
      Boolean(dto.service_type),
    );
    this.validateRecurrenceDate(date, serviceType);
    const conflictingSchedule =
      await this.schedulesRepository.findScheduleOnDate(
        date,
        serviceType.code,
        id,
      );

    if (conflictingSchedule) {
      throw new BadRequestException(
        `A ${serviceType.name} schedule already exists for this date`,
      );
    }
    const update: any = { ...dto, date };

    if (dto.assignments) {
      update.assignments = await this.validateAndBuildAssignments(
        dto.assignments,
        date,
        serviceType,
        id,
      );
    } else if (dto.service_type) {
      this.validateServiceStructure(existing.assignments as any, serviceType);
    }

    const schedule = await this.schedulesRepository.updateRecord(
      { _id: id } as any,
      update,
    );

    if (!schedule) {
      throw new NotFoundException('Schedule not found');
    }

    return schedule;
  }

  async updateScheduleLineup(
    id: string,
    lineup: string,
    userId: string,
    userRole: UserRole,
  ) {
    const schedule = await this.getScheduleById(id);

    if (
      userRole !== UserRole.Admin &&
      userRole !== UserRole.SuperAdmin
    ) {
      const worker = await this.workersService.findWorkerByUserId(userId);
      const isAssignedLeader = worker && schedule.assignments.some((assignment) => {
        return (
          assignment.role === WorkerRole.Leader &&
          assignment.worker_id.toString() === worker._id.toString()
        );
      });

      if (!isAssignedLeader) {
        throw new ForbiddenException(
          'Only the assigned leader can edit this schedule lineup',
        );
      }
    }

    const updatedSchedule = await this.schedulesRepository.updateRecord(
      { _id: id } as any,
      { lineup: lineup.trim() } as any,
    );

    if (!updatedSchedule) {
      throw new NotFoundException('Schedule not found');
    }

    return updatedSchedule;
  }

  async deleteScheduleById(id: string) {
    const result = await this.schedulesRepository.deleteRecord({ _id: id } as any);

    if (!result.deletedCount) {
      throw new NotFoundException('Schedule not found');
    }

    return result;
  }

  @Cron('0 0 * * 1', {
    timeZone: process.env.CHURCH_TIMEZONE || 'Asia/Singapore',
  })
  async syncPastScheduleStatuses() {
    const throughDate = this.getLastCompletedLocalDate(new Date());

    if (!throughDate) {
      return { modifiedCount: 0 };
    }

    return await this.schedulesRepository.markSchedulesInactiveThroughDate(
      throughDate,
    );
  }

  private async validateAndBuildAssignments(
    assignments: ScheduleAssignmentDto[],
    date: Date,
    serviceType: any,
    excludeScheduleId?: string,
  ) {
    if (!assignments?.length) {
      throw new BadRequestException('At least one assignment is required');
    }

    const slottedAssignments = this.validateServiceStructure(
      assignments,
      serviceType,
    );
    this.validateNoDuplicateWorkers(slottedAssignments);

    const workerIds = slottedAssignments.map(
      (assignment) => new Types.ObjectId(assignment.worker_id),
    );
    const conflict = await this.schedulesRepository.findWorkerConflictOnDate(
      date,
      workerIds,
      excludeScheduleId,
    );

    if (conflict) {
      throw new BadRequestException(
        'A worker is already assigned to another schedule on this date',
      );
    }

    return await Promise.all(
      slottedAssignments.map(async (assignment) => {
        const worker = await this.workersService.getWorkerById(
          assignment.worker_id,
        );

        if (worker.status !== WorkerStatus.Active) {
          throw new BadRequestException('Inactive workers cannot be assigned');
        }

        if (!worker.roles?.includes(assignment.role)) {
          throw new BadRequestException(
            `${worker.name} cannot be assigned to ${assignment.role}`,
          );
        }

        const slot = serviceType.assignment_slots.find(
          (item) => item.key === assignment.slot_key,
        );
        const eligibility =
          slot?.worker_eligibility_override ??
          serviceType.worker_eligibility;
        const workerGroupIds = await this.workersService.getWorkerGroupIds(
          worker,
        );

        if (!this.isWorkerEligible(workerGroupIds, eligibility)) {
          throw new BadRequestException(
            `${worker.name} is not eligible for ${slot?.label ?? assignment.role} in ${serviceType.name}`,
          );
        }

        return {
          slot_key: assignment.slot_key,
          role: assignment.role,
          worker_id: new Types.ObjectId(assignment.worker_id),
          worker_name: worker.name,
        };
      }),
    );
  }

  private validateServiceStructure(
    assignments: ScheduleAssignmentDto[],
    serviceType: any,
  ) {
    const slots = [...serviceType.assignment_slots].sort(
      (a, b) => a.display_order - b.display_order,
    );
    const usedSlotKeys = new Set<string>();
    const resolved = assignments.map((assignment) => {
      const slot = assignment.slot_key
        ? slots.find((item) => item.key === assignment.slot_key)
        : slots.find(
            (item) =>
              !usedSlotKeys.has(item.key) &&
              item.allowed_roles.includes(assignment.role),
          );

      if (!slot || !slot.allowed_roles.includes(assignment.role)) {
        throw new BadRequestException(
          `${assignment.role} is not supported by ${serviceType.name}`,
        );
      }

      if (usedSlotKeys.has(slot.key)) {
        throw new BadRequestException(
          `Assignment slot "${slot.label}" can only be filled once`,
        );
      }

      usedSlotKeys.add(slot.key);
      return { ...assignment, slot_key: slot.key };
    });
    const missingSlots = slots
      .filter((slot) => slot.required && !usedSlotKeys.has(slot.key))
      .map((slot) => slot.label);

    if (missingSlots.length) {
      throw new BadRequestException(
        `Missing required assignments: ${missingSlots.join(', ')}`,
      );
    }

    return resolved;
  }

  private validateNoDuplicateWorkers(assignments: ScheduleAssignmentDto[]) {
    const rolesByWorker = assignments.reduce<Map<string, WorkerRole[]>>(
      (roles, assignment) => {
        const workerRoles = roles.get(assignment.worker_id) ?? [];
        workerRoles.push(assignment.role);
        roles.set(assignment.worker_id, workerRoles);
        return roles;
      },
      new Map(),
    );
    const hasUnsupportedDuplicate = [...rolesByWorker.values()].some((roles) => {
      if (roles.length === 1) {
        return false;
      }

      const roleSet = new Set(roles);
      return !(
        roles.length === 2 &&
        roleSet.has(WorkerRole.Acoustic) &&
        (roleSet.has(WorkerRole.Leader) || roleSet.has(WorkerRole.Backup))
      );
    });

    if (hasUnsupportedDuplicate) {
      throw new BadRequestException(
        'A worker cannot be assigned to multiple roles in the same schedule, except Leader/Acoustic or Backup/Acoustic',
      );
    }
  }

  private isWorkerEligible(
    workerGroupIds: string[],
    eligibility: {
      mode: WorkerEligibilityMode;
      allowed_group_ids?: unknown[];
    },
  ) {
    if (eligibility.mode === WorkerEligibilityMode.Any) {
      return true;
    }

    const allowedIds = new Set(
      (eligibility.allowed_group_ids ?? []).map(String),
    );
    return workerGroupIds.some((id) => allowedIds.has(String(id)));
  }

  private validateRecurrenceDate(date: Date, serviceType: any) {
    if (
      serviceType.recurrence.type === 'weekly' &&
      date.getUTCDay() !== serviceType.recurrence.weekday
    ) {
      throw new BadRequestException(
        `${serviceType.name} schedules must be assigned on the configured weekday`,
      );
    }
  }

  private normalizeScheduleDate(value: string | Date) {
    const date = new Date(value);

    if (Number.isNaN(date.getTime())) {
      throw new BadRequestException('Invalid schedule date');
    }

    date.setUTCHours(0, 0, 0, 0);

    return date;
  }

  private getStatusForDate(date: Date) {
    const throughDate = this.getLastCompletedLocalDate(new Date());

    if (throughDate && date <= throughDate) {
      return ScheduleStatus.Inactive;
    }

    return ScheduleStatus.Active;
  }

  private getLastCompletedLocalDate(now: Date) {
    const offsetMinutes = Number(process.env.CHURCH_TIMEZONE_OFFSET_MINUTES || 480);
    const localNow = new Date(now.getTime() + offsetMinutes * 60 * 1000);

    if (localNow.getUTCDay() === 0) {
      return null;
    }

    const completedLocalDate = new Date(
      Date.UTC(
        localNow.getUTCFullYear(),
        localNow.getUTCMonth(),
        localNow.getUTCDate(),
      ),
    );

    completedLocalDate.setUTCDate(completedLocalDate.getUTCDate() - 1);

    return completedLocalDate;
  }

  private getCurrentLocalDate() {
    const offsetMinutes = Number(process.env.CHURCH_TIMEZONE_OFFSET_MINUTES || 480);
    const localNow = new Date(Date.now() + offsetMinutes * 60 * 1000);

    return new Date(Date.UTC(
      localNow.getUTCFullYear(),
      localNow.getUTCMonth(),
      localNow.getUTCDate(),
    ));
  }
}
