import { Injectable } from '@nestjs/common';
import { ServiceType } from 'src/common/enums/service-type.enum';
import { WorkerLabel } from 'src/common/enums/worker-label.enum';
import { WorkerRole } from 'src/common/enums/worker-role.enum';
import { WorkerStatus } from 'src/common/enums/worker-status.enum';
import { WorkersService } from 'src/workers/workers.service';
import { AutoGenerationPreviewDto } from './dto/auto-generation-preview.dto';
import { SchedulesRepository } from './repositories/schedules.repository';

type PreviewStatus = 'generated' | 'skipped' | 'needs_attention';

interface WorkerCandidate {
  _id: unknown;
  name: string;
  roles: WorkerRole[];
  label?: WorkerLabel;
  status: WorkerStatus;
}

interface ScheduleLike {
  date: Date | string;
  service_type?: ServiceType;
  assignments?: Array<{
    worker_id?: unknown;
  }>;
}

interface FairnessScore {
  count: number;
  lastAssignedTime: number;
}

export interface AutoGeneratedAssignment {
  role: WorkerRole;
  worker_id: string;
  worker_name: string;
}

export interface AutoGenerationPreviewRow {
  date: string;
  service_type: ServiceType;
  status: PreviewStatus;
  assignments: AutoGeneratedAssignment[];
  warnings: string[];
}

@Injectable()
export class ScheduleAutoGenerationService {
  private readonly mainRequiredRoles = [
    WorkerRole.Leader,
    WorkerRole.Acoustic,
    WorkerRole.Bass,
    WorkerRole.Drums,
  ];

  private readonly mainOptionalRoles = [
    WorkerRole.Backup,
    WorkerRole.Electric,
    WorkerRole.Keyboard,
  ];

  private readonly serviceWeekdays: Record<ServiceType, number> = {
    [ServiceType.Main]: 0,
    [ServiceType.Youth]: 6,
    [ServiceType.Midweek]: 3,
    [ServiceType.SumAg]: 0,
    [ServiceType.Yanson]: 0,
  };

  constructor(
    private readonly schedulesRepository: SchedulesRepository,
    private readonly workersService: WorkersService,
  ) {}

  async preview(dto: AutoGenerationPreviewDto) {
    const serviceType = dto.service_type ?? ServiceType.Main;
    const includeOptionalRoles = dto.includeOptionalRoles ?? true;
    const allowYouthBackupFallback = dto.allowYouthBackupFallback ?? true;
    const monthStart = new Date(Date.UTC(dto.year, dto.month - 1, 1));
    const nextMonthStart = new Date(Date.UTC(dto.year, dto.month, 1));
    const previousMonthStart = new Date(Date.UTC(dto.year, dto.month - 2, 1));

    const [activeWorkersResult, monthSchedules, recentServiceSchedules] =
      await Promise.all([
        this.workersService.getWorkers(WorkerStatus.Active),
        this.schedulesRepository.findSchedulesInDateRange(
          monthStart,
          nextMonthStart,
        ),
        this.schedulesRepository.findSchedulesInDateRange(
          previousMonthStart,
          nextMonthStart,
          serviceType,
        ),
      ]);

    const activeWorkers = activeWorkersResult.items as unknown as WorkerCandidate[];
    const fairnessScores = this.buildFairnessScores(
      activeWorkers,
      recentServiceSchedules as ScheduleLike[],
    );
    const monthSchedulesByDate = this.groupSchedulesByDate(
      monthSchedules as ScheduleLike[],
    );

    const rows = this.getDatesInMonth(
      dto.year,
      dto.month,
      this.serviceWeekdays[serviceType],
    ).map((date) => {
      const dateKey = this.toDateKey(date);
      const schedulesOnDate = monthSchedulesByDate.get(dateKey) ?? [];
      const existingServiceSchedule = schedulesOnDate.find((schedule) => {
        return schedule.service_type === serviceType;
      });

      if (existingServiceSchedule) {
        return {
          date: dateKey,
          service_type: serviceType,
          status: 'skipped' as const,
          assignments: [],
          warnings: [`A ${this.getServiceLabel(serviceType)} schedule already exists for this date.`],
        };
      }

      const usedWorkerIds = this.getAssignedWorkerIds(schedulesOnDate);
      const assignments: AutoGeneratedAssignment[] = [];
      const warnings: string[] = [];

      const assignRole = (role: WorkerRole, required: boolean) => {
        const worker = this.selectWorkerForRole(
          role,
          activeWorkers,
          usedWorkerIds,
          fairnessScores,
          allowYouthBackupFallback,
          serviceType,
        );

        if (!worker) {
          if (required) {
            warnings.push(`Missing required role: ${role}`);
          }
          return;
        }

        const workerId = this.toId(worker._id);
        usedWorkerIds.add(workerId);
        assignments.push({
          role,
          worker_id: workerId,
          worker_name: worker.name,
        });
        this.incrementFairnessScore(fairnessScores, workerId, date);
      };

      if (serviceType === ServiceType.Main) {
        this.mainRequiredRoles.forEach((role) => assignRole(role, true));
      } else {
        assignRole(WorkerRole.Leader, true);

        if (serviceType === ServiceType.Midweek) {
          const instrument = this.selectFlexibleRoleWorker(
            [WorkerRole.Acoustic, WorkerRole.Keyboard],
            activeWorkers,
            usedWorkerIds,
            fairnessScores,
          );

          if (!instrument) {
            warnings.push('Missing required role: Acoustic/Keyboard');
          } else {
            const workerId = this.toId(instrument.worker._id);
            usedWorkerIds.add(workerId);
            assignments.push({
              role: instrument.role,
              worker_id: workerId,
              worker_name: instrument.worker.name,
            });
            this.incrementFairnessScore(fairnessScores, workerId, date);
          }
        } else {
          assignRole(WorkerRole.Acoustic, true);
        }
      }

      if (serviceType !== ServiceType.Main && includeOptionalRoles) {
        assignRole(WorkerRole.Bass, false);
        const percussion = this.selectPercussionWorker(
          activeWorkers,
          usedWorkerIds,
          fairnessScores,
        );

        if (percussion) {
          const workerId = this.toId(percussion.worker._id);
          usedWorkerIds.add(workerId);
          assignments.push({
            role: percussion.role,
            worker_id: workerId,
            worker_name: percussion.worker.name,
          });
          this.incrementFairnessScore(fairnessScores, workerId, date);
        }
      }

      if (serviceType === ServiceType.Main && includeOptionalRoles) {
        this.mainOptionalRoles.forEach((role) => assignRole(role, false));
      }

      return {
        date: dateKey,
        service_type: serviceType,
        status: warnings.length ? 'needs_attention' as const : 'generated' as const,
        assignments,
        warnings,
      };
    });

    return {
      year: dto.year,
      month: dto.month,
      service_type: serviceType,
      rows,
    };
  }

  isGenerationDate(serviceType: ServiceType, date: Date) {
    return date.getUTCDay() === this.serviceWeekdays[serviceType];
  }

  private selectWorkerForRole(
    role: WorkerRole,
    workers: WorkerCandidate[],
    usedWorkerIds: Set<string>,
    fairnessScores: Map<string, FairnessScore>,
    allowYouthBackupFallback: boolean,
    serviceType: ServiceType,
  ) {
    const roleCandidates = workers.filter((worker) => {
      return (
        worker.status === WorkerStatus.Active &&
        worker.roles?.includes(role) &&
        !usedWorkerIds.has(this.toId(worker._id))
      );
    });

    if (serviceType !== ServiceType.Main) {
      return this.pickFairestWorker(roleCandidates, fairnessScores);
    }

    if (role === WorkerRole.Backup) {
      const mainBackupCandidates = roleCandidates.filter((worker) => {
        return this.getWorkerLabel(worker) === WorkerLabel.Main;
      });

      if (mainBackupCandidates.length) {
        return this.pickFairestWorker(mainBackupCandidates, fairnessScores);
      }

      if (allowYouthBackupFallback) {
        return this.pickFairestWorker(
          roleCandidates.filter((worker) => {
            return this.getWorkerLabel(worker) === WorkerLabel.Youth;
          }),
          fairnessScores,
        );
      }

      return undefined;
    }

    return this.pickFairestWorker(
      roleCandidates.filter((worker) => {
        return this.getWorkerLabel(worker) === WorkerLabel.Main;
      }),
      fairnessScores,
    );
  }

  private selectFlexibleRoleWorker(
    roles: WorkerRole[],
    workers: WorkerCandidate[],
    usedWorkerIds: Set<string>,
    fairnessScores: Map<string, FairnessScore>,
  ) {
    const candidates = workers.filter((worker) => {
      return (
        worker.status === WorkerStatus.Active &&
        roles.some((role) => worker.roles?.includes(role)) &&
        !usedWorkerIds.has(this.toId(worker._id))
      );
    });
    const worker = this.pickFairestWorker(candidates, fairnessScores);

    if (!worker) {
      return undefined;
    }

    return {
      worker,
      role: roles.find((role) => worker.roles?.includes(role))!,
    };
  }

  private selectPercussionWorker(
    workers: WorkerCandidate[],
    usedWorkerIds: Set<string>,
    fairnessScores: Map<string, FairnessScore>,
  ) {
    const candidates = workers.filter((worker) => {
      return (
        worker.status === WorkerStatus.Active &&
        (worker.roles?.includes(WorkerRole.Drums) ||
          worker.roles?.includes(WorkerRole.Beatbox)) &&
        !usedWorkerIds.has(this.toId(worker._id))
      );
    });
    const worker = this.pickFairestWorker(candidates, fairnessScores);

    if (!worker) {
      return undefined;
    }

    return {
      worker,
      role: worker.roles.includes(WorkerRole.Drums)
        ? WorkerRole.Drums
        : WorkerRole.Beatbox,
    };
  }

  private pickFairestWorker(
    candidates: WorkerCandidate[],
    fairnessScores: Map<string, FairnessScore>,
  ) {
    return [...candidates].sort((a, b) => {
      const aScore = fairnessScores.get(this.toId(a._id)) ?? {
        count: 0,
        lastAssignedTime: 0,
      };
      const bScore = fairnessScores.get(this.toId(b._id)) ?? {
        count: 0,
        lastAssignedTime: 0,
      };

      if (aScore.count !== bScore.count) {
        return aScore.count - bScore.count;
      }

      if (aScore.lastAssignedTime !== bScore.lastAssignedTime) {
        return aScore.lastAssignedTime - bScore.lastAssignedTime;
      }

      return a.name.localeCompare(b.name);
    })[0];
  }

  private buildFairnessScores(
    workers: WorkerCandidate[],
    recentServiceSchedules: ScheduleLike[],
  ) {
    const scores = new Map<string, FairnessScore>();

    workers.forEach((worker) => {
      scores.set(this.toId(worker._id), {
        count: 0,
        lastAssignedTime: 0,
      });
    });

    recentServiceSchedules.forEach((schedule) => {
      const assignedTime = this.toDate(schedule.date).getTime();
      schedule.assignments?.forEach((assignment) => {
        if (!assignment.worker_id) {
          return;
        }

        const workerId = this.toId(assignment.worker_id);
        const score = scores.get(workerId) ?? {
          count: 0,
          lastAssignedTime: 0,
        };

        scores.set(workerId, {
          count: score.count + 1,
          lastAssignedTime: Math.max(score.lastAssignedTime, assignedTime),
        });
      });
    });

    return scores;
  }

  private incrementFairnessScore(
    scores: Map<string, FairnessScore>,
    workerId: string,
    date: Date,
  ) {
    const score = scores.get(workerId) ?? {
      count: 0,
      lastAssignedTime: 0,
    };

    scores.set(workerId, {
      count: score.count + 1,
      lastAssignedTime: Math.max(score.lastAssignedTime, date.getTime()),
    });
  }

  private getAssignedWorkerIds(schedules: ScheduleLike[]) {
    const workerIds = new Set<string>();

    schedules.forEach((schedule) => {
      schedule.assignments?.forEach((assignment) => {
        if (assignment.worker_id) {
          workerIds.add(this.toId(assignment.worker_id));
        }
      });
    });

    return workerIds;
  }

  private groupSchedulesByDate(schedules: ScheduleLike[]) {
    return schedules.reduce<Map<string, ScheduleLike[]>>((acc, schedule) => {
      const dateKey = this.toDateKey(schedule.date);
      const schedulesOnDate = acc.get(dateKey) ?? [];
      schedulesOnDate.push(schedule);
      acc.set(dateKey, schedulesOnDate);

      return acc;
    }, new Map());
  }

  private getDatesInMonth(year: number, month: number, weekday: number) {
    const dates: Date[] = [];
    const current = new Date(Date.UTC(year, month - 1, 1));

    while (current.getUTCMonth() === month - 1) {
      if (current.getUTCDay() === weekday) {
        dates.push(new Date(current));
      }

      current.setUTCDate(current.getUTCDate() + 1);
    }

    return dates;
  }

  private getServiceLabel(serviceType: ServiceType) {
    const labels: Record<ServiceType, string> = {
      [ServiceType.Main]: 'Main service',
      [ServiceType.Youth]: 'Youth service',
      [ServiceType.Midweek]: 'Midweek service',
      [ServiceType.SumAg]: 'Sum-ag service',
      [ServiceType.Yanson]: 'Yanson service',
    };

    return labels[serviceType];
  }

  private getWorkerLabel(worker: WorkerCandidate) {
    return worker.label ?? WorkerLabel.Main;
  }

  private toDate(value: Date | string) {
    return value instanceof Date ? value : new Date(value);
  }

  private toDateKey(value: Date | string) {
    return this.toDate(value).toISOString().slice(0, 10);
  }

  private toId(value: unknown) {
    if (typeof value === 'string') {
      return value;
    }

    if (value && typeof (value as { toString: () => string }).toString === 'function') {
      return (value as { toString: () => string }).toString();
    }

    return String(value);
  }
}
