import { Test, TestingModule } from '@nestjs/testing';
import { JwtModule } from '@nestjs/jwt';
import { JwtAuthGuard } from 'src/auth/guards/jwt-auth.guard';
import { RolesGuard } from 'src/auth/guards/roles.guard';
import { SchedulesController } from './schedules.controller';
import { SchedulesService } from './schedules.service';

describe('SchedulesController', () => {
  let controller: SchedulesController;

  beforeEach(async () => {
    const module: TestingModule = await Test.createTestingModule({
      imports: [JwtModule.register({})],
      controllers: [SchedulesController],
      providers: [
        JwtAuthGuard,
        RolesGuard,
        {
          provide: SchedulesService,
          useValue: {
            getAllSchedules: jest.fn(),
            syncPastScheduleStatuses: jest.fn(),
            previewAutoGeneratedSchedules: jest.fn(),
            confirmAutoGeneratedSchedules: jest.fn(),
            getScheduleById: jest.fn(),
            createSchedule: jest.fn(),
            updateScheduleById: jest.fn(),
            deleteScheduleById: jest.fn(),
          },
        },
      ],
    }).compile();

    controller = module.get<SchedulesController>(SchedulesController);
  });

  it('should be defined', () => {
    expect(controller).toBeDefined();
  });
});
