import {
  BadRequestException,
  Injectable,
  NotFoundException,
} from '@nestjs/common';
import { Cron } from '@nestjs/schedule';
import { Types } from 'mongoose';
import { ScheduleStatus } from 'src/common/enums/schedule-status.enum';
import { ServiceType } from 'src/common/enums/service-type.enum';
import { WorkerRole } from 'src/common/enums/worker-role.enum';
import { WorkerStatus } from 'src/common/enums/worker-status.enum';
import { WorkersService } from 'src/workers/workers.service';
import { AutoGenerationConfirmDto } from './dto/auto-generation-confirm.dto';
import { AutoGenerationPreviewDto } from './dto/auto-generation-preview.dto';
import { CreateScheduleDTO } from './dto/create-schedule.dto';
import { ScheduleAssignmentDto } from './dto/schedule-assignment.dto';
import { UpdateScheduleDto } from './dto/update-schedule.dto';
import { ScheduleAutoGenerationService } from './schedule-auto-generation.service';
import { SchedulesRepository } from './repositories/schedules.repository';

@Injectable()
export class SchedulesService {
  private readonly mainRequiredRoles = [
    WorkerRole.Leader,
    WorkerRole.Acoustic,
    WorkerRole.Bass,
    WorkerRole.Drums,
  ];

  private readonly standardRequiredRoles = [
    WorkerRole.Leader,
    WorkerRole.Acoustic,
  ];

  constructor(
    private readonly schedulesRepository: SchedulesRepository,
    private readonly workersService: WorkersService,
    private readonly scheduleAutoGenerationService: ScheduleAutoGenerationService,
  ) {}

  async getAllSchedules(query: any = {}) {
    const filter: any = {};

    if (query.status) {
      filter.status = query.status;
    }

    if (query.service_type) {
      filter.service_type = query.service_type;
    }

    return await this.schedulesRepository.getRecords(filter, 1, 100, 'asc', 'date');
  }

  async getScheduleById(id: string) {
    const schedule = await this.schedulesRepository.getRecordById(id);

    if (!schedule) {
      throw new NotFoundException('Schedule not found');
    }

    return schedule;
  }

  async createSchedule(dto: CreateScheduleDTO) {
    const date = this.normalizeScheduleDate(dto.date);
    const serviceType = dto.service_type || ServiceType.Main;
    const assignments = await this.validateAndBuildAssignments(
      dto.assignments,
      date,
      serviceType,
    );

    return await this.schedulesRepository.insertRecord({
      date,
      service_type: serviceType,
      status: dto.status || this.getStatusForDate(date),
      assignments,
      songs: dto.songs || [],
      lineup: dto.lineup,
      notes: dto.notes,
    } as any);
  }

  async previewAutoGeneratedSchedules(dto: AutoGenerationPreviewDto) {
    return await this.scheduleAutoGenerationService.preview(dto);
  }

  async confirmAutoGeneratedSchedules(dto: AutoGenerationConfirmDto) {
    const seenDates = new Set<string>();
    const preparedSchedules: any[] = [];

    for (const schedule of dto.schedules) {
      const date = this.normalizeScheduleDate(schedule.date);
      const dateKey = date.toISOString().slice(0, 10);

      if (seenDates.has(dateKey)) {
        throw new BadRequestException(
          `Duplicate generated schedule date: ${dateKey}`,
        );
      }

      seenDates.add(dateKey);

      const existingMainSchedule =
        await this.schedulesRepository.findMainScheduleOnDate(date);

      if (existingMainSchedule) {
        throw new BadRequestException(
          `A Main service schedule already exists for ${dateKey}`,
        );
      }

      const assignments = await this.validateAndBuildAssignments(
        schedule.assignments,
        date,
        ServiceType.Main,
      );

      preparedSchedules.push({
        date,
        service_type: ServiceType.Main,
        status: this.getStatusForDate(date),
        assignments,
        songs: schedule.songs || [],
        lineup: schedule.lineup,
        notes: schedule.notes,
      });
    }

    const createdSchedules: any[] = [];

    for (const schedule of preparedSchedules) {
      createdSchedules.push(
        await this.schedulesRepository.insertRecord(schedule as any),
      );
    }

    return createdSchedules;
  }

  async updateScheduleById(id: string, dto: UpdateScheduleDto) {
    const existing = await this.getScheduleById(id);
    const date = dto.date ? this.normalizeScheduleDate(dto.date) : existing.date;
    const serviceType = dto.service_type || existing.service_type || ServiceType.Main;
    const update: any = { ...dto, date };

    if (dto.assignments) {
      update.assignments = await this.validateAndBuildAssignments(
        dto.assignments,
        date,
        serviceType,
        id,
      );
    } else if (dto.service_type) {
      this.validateRequiredRoles(existing.assignments as any, serviceType);
    }

    const schedule = await this.schedulesRepository.updateRecord(
      { _id: id } as any,
      update,
    );

    if (!schedule) {
      throw new NotFoundException('Schedule not found');
    }

    return schedule;
  }

  async deleteScheduleById(id: string) {
    const result = await this.schedulesRepository.deleteRecord({ _id: id } as any);

    if (!result.deletedCount) {
      throw new NotFoundException('Schedule not found');
    }

    return result;
  }

  @Cron('0 0 * * 1', {
    timeZone: process.env.CHURCH_TIMEZONE || 'Asia/Singapore',
  })
  async syncPastScheduleStatuses() {
    const throughDate = this.getLastCompletedLocalDate(new Date());

    if (!throughDate) {
      return { modifiedCount: 0 };
    }

    return await this.schedulesRepository.markSchedulesInactiveThroughDate(
      throughDate,
    );
  }

  private async validateAndBuildAssignments(
    assignments: ScheduleAssignmentDto[],
    date: Date,
    serviceType: ServiceType,
    excludeScheduleId?: string,
  ) {
    if (!assignments?.length) {
      throw new BadRequestException('At least one assignment is required');
    }

    this.validateRequiredRoles(assignments, serviceType);
    this.validateNoDuplicateWorkers(assignments);

    const workerIds = assignments.map(
      (assignment) => new Types.ObjectId(assignment.worker_id),
    );
    const conflict = await this.schedulesRepository.findWorkerConflictOnDate(
      date,
      workerIds,
      excludeScheduleId,
    );

    if (conflict) {
      throw new BadRequestException(
        'A worker is already assigned to another schedule on this date',
      );
    }

    return await Promise.all(
      assignments.map(async (assignment) => {
        const worker = await this.workersService.getWorkerById(
          assignment.worker_id,
        );

        if (worker.status !== WorkerStatus.Active) {
          throw new BadRequestException('Inactive workers cannot be assigned');
        }

        if (!worker.roles?.includes(assignment.role)) {
          throw new BadRequestException(
            `${worker.name} cannot be assigned to ${assignment.role}`,
          );
        }

        return {
          role: assignment.role,
          worker_id: new Types.ObjectId(assignment.worker_id),
          worker_name: worker.name,
        };
      }),
    );
  }

  private validateRequiredRoles(
    assignments: Pick<ScheduleAssignmentDto, 'role'>[],
    serviceType: ServiceType,
  ) {
    const assignedRoles = new Set(assignments.map((assignment) => assignment.role));
    const missingRoles = this.getRequiredRoles(serviceType).filter(
      (role) => !assignedRoles.has(role),
    );

    if (missingRoles.length) {
      throw new BadRequestException(
        `Missing required roles: ${missingRoles.join(', ')}`,
      );
    }
  }

  private getRequiredRoles(serviceType: ServiceType) {
    return serviceType === ServiceType.Main
      ? this.mainRequiredRoles
      : this.standardRequiredRoles;
  }

  private validateNoDuplicateWorkers(assignments: ScheduleAssignmentDto[]) {
    const workerIds = assignments.map((assignment) => assignment.worker_id);
    const uniqueWorkerIds = new Set(workerIds);

    if (uniqueWorkerIds.size !== workerIds.length) {
      throw new BadRequestException(
        'A worker cannot be assigned to multiple roles in the same schedule',
      );
    }
  }

  private normalizeScheduleDate(value: string | Date) {
    const date = new Date(value);

    if (Number.isNaN(date.getTime())) {
      throw new BadRequestException('Invalid schedule date');
    }

    date.setUTCHours(0, 0, 0, 0);

    return date;
  }

  private getStatusForDate(date: Date) {
    const throughDate = this.getLastCompletedLocalDate(new Date());

    if (throughDate && date <= throughDate) {
      return ScheduleStatus.Inactive;
    }

    return ScheduleStatus.Active;
  }

  private getLastCompletedLocalDate(now: Date) {
    const offsetMinutes = Number(process.env.CHURCH_TIMEZONE_OFFSET_MINUTES || 480);
    const localNow = new Date(now.getTime() + offsetMinutes * 60 * 1000);

    if (localNow.getUTCDay() === 0) {
      return null;
    }

    const completedLocalDate = new Date(
      Date.UTC(
        localNow.getUTCFullYear(),
        localNow.getUTCMonth(),
        localNow.getUTCDate(),
      ),
    );

    completedLocalDate.setUTCDate(completedLocalDate.getUTCDate() - 1);

    return completedLocalDate;
  }
}
