import { Injectable } from '@nestjs/common';
import { ServiceType } from 'src/common/enums/service-type.enum';
import { WorkerLabel } from 'src/common/enums/worker-label.enum';
import { WorkerRole } from 'src/common/enums/worker-role.enum';
import { WorkerStatus } from 'src/common/enums/worker-status.enum';
import { WorkersService } from 'src/workers/workers.service';
import { AutoGenerationPreviewDto } from './dto/auto-generation-preview.dto';
import { SchedulesRepository } from './repositories/schedules.repository';

type PreviewStatus = 'generated' | 'skipped' | 'needs_attention';

interface WorkerCandidate {
  _id: unknown;
  name: string;
  roles: WorkerRole[];
  label?: WorkerLabel;
  status: WorkerStatus;
}

interface ScheduleLike {
  date: Date | string;
  service_type?: ServiceType;
  assignments?: Array<{
    worker_id?: unknown;
  }>;
}

interface FairnessScore {
  count: number;
  lastAssignedTime: number;
}

export interface AutoGeneratedAssignment {
  role: WorkerRole;
  worker_id: string;
  worker_name: string;
}

export interface AutoGenerationPreviewRow {
  date: string;
  service_type: ServiceType.Main;
  status: PreviewStatus;
  assignments: AutoGeneratedAssignment[];
  warnings: string[];
}

@Injectable()
export class ScheduleAutoGenerationService {
  private readonly requiredRoles = [
    WorkerRole.Leader,
    WorkerRole.Acoustic,
    WorkerRole.Bass,
    WorkerRole.Drums,
  ];

  private readonly optionalRoles = [
    WorkerRole.Backup,
    WorkerRole.Electric,
    WorkerRole.Keyboard,
  ];

  constructor(
    private readonly schedulesRepository: SchedulesRepository,
    private readonly workersService: WorkersService,
  ) {}

  async preview(dto: AutoGenerationPreviewDto) {
    const includeOptionalRoles = dto.includeOptionalRoles ?? true;
    const allowYouthBackupFallback = dto.allowYouthBackupFallback ?? true;
    const monthStart = new Date(Date.UTC(dto.year, dto.month - 1, 1));
    const nextMonthStart = new Date(Date.UTC(dto.year, dto.month, 1));
    const previousMonthStart = new Date(Date.UTC(dto.year, dto.month - 2, 1));

    const [activeWorkersResult, monthSchedules, recentMainSchedules] =
      await Promise.all([
        this.workersService.getWorkers(WorkerStatus.Active),
        this.schedulesRepository.findSchedulesInDateRange(
          monthStart,
          nextMonthStart,
        ),
        this.schedulesRepository.findSchedulesInDateRange(
          previousMonthStart,
          nextMonthStart,
          ServiceType.Main,
        ),
      ]);

    const activeWorkers = activeWorkersResult.items as unknown as WorkerCandidate[];
    const fairnessScores = this.buildFairnessScores(
      activeWorkers,
      recentMainSchedules as ScheduleLike[],
    );
    const monthSchedulesByDate = this.groupSchedulesByDate(
      monthSchedules as ScheduleLike[],
    );

    const rows = this.getSundaysInMonth(dto.year, dto.month).map((date) => {
      const dateKey = this.toDateKey(date);
      const schedulesOnDate = monthSchedulesByDate.get(dateKey) ?? [];
      const existingMainSchedule = schedulesOnDate.find((schedule) => {
        return schedule.service_type === ServiceType.Main;
      });

      if (existingMainSchedule) {
        return {
          date: dateKey,
          service_type: ServiceType.Main,
          status: 'skipped' as const,
          assignments: [],
          warnings: ['A Main service schedule already exists for this date.'],
        };
      }

      const usedWorkerIds = this.getAssignedWorkerIds(schedulesOnDate);
      const assignments: AutoGeneratedAssignment[] = [];
      const warnings: string[] = [];

      const assignRole = (role: WorkerRole, required: boolean) => {
        const worker = this.selectWorkerForRole(
          role,
          activeWorkers,
          usedWorkerIds,
          fairnessScores,
          allowYouthBackupFallback,
        );

        if (!worker) {
          if (required) {
            warnings.push(`Missing required role: ${role}`);
          }
          return;
        }

        const workerId = this.toId(worker._id);
        usedWorkerIds.add(workerId);
        assignments.push({
          role,
          worker_id: workerId,
          worker_name: worker.name,
        });
        this.incrementFairnessScore(fairnessScores, workerId, date);
      };

      this.requiredRoles.forEach((role) => assignRole(role, true));

      if (includeOptionalRoles) {
        this.optionalRoles.forEach((role) => assignRole(role, false));
      }

      return {
        date: dateKey,
        service_type: ServiceType.Main,
        status: warnings.length ? 'needs_attention' as const : 'generated' as const,
        assignments,
        warnings,
      };
    });

    return {
      year: dto.year,
      month: dto.month,
      service_type: ServiceType.Main,
      rows,
    };
  }

  private selectWorkerForRole(
    role: WorkerRole,
    workers: WorkerCandidate[],
    usedWorkerIds: Set<string>,
    fairnessScores: Map<string, FairnessScore>,
    allowYouthBackupFallback: boolean,
  ) {
    const roleCandidates = workers.filter((worker) => {
      return (
        worker.status === WorkerStatus.Active &&
        worker.roles?.includes(role) &&
        !usedWorkerIds.has(this.toId(worker._id))
      );
    });

    if (role === WorkerRole.Backup) {
      const mainBackupCandidates = roleCandidates.filter((worker) => {
        return this.getWorkerLabel(worker) === WorkerLabel.Main;
      });

      if (mainBackupCandidates.length) {
        return this.pickFairestWorker(mainBackupCandidates, fairnessScores);
      }

      if (allowYouthBackupFallback) {
        return this.pickFairestWorker(
          roleCandidates.filter((worker) => {
            return this.getWorkerLabel(worker) === WorkerLabel.Youth;
          }),
          fairnessScores,
        );
      }

      return undefined;
    }

    return this.pickFairestWorker(
      roleCandidates.filter((worker) => {
        return this.getWorkerLabel(worker) === WorkerLabel.Main;
      }),
      fairnessScores,
    );
  }

  private pickFairestWorker(
    candidates: WorkerCandidate[],
    fairnessScores: Map<string, FairnessScore>,
  ) {
    return [...candidates].sort((a, b) => {
      const aScore = fairnessScores.get(this.toId(a._id)) ?? {
        count: 0,
        lastAssignedTime: 0,
      };
      const bScore = fairnessScores.get(this.toId(b._id)) ?? {
        count: 0,
        lastAssignedTime: 0,
      };

      if (aScore.count !== bScore.count) {
        return aScore.count - bScore.count;
      }

      if (aScore.lastAssignedTime !== bScore.lastAssignedTime) {
        return aScore.lastAssignedTime - bScore.lastAssignedTime;
      }

      return a.name.localeCompare(b.name);
    })[0];
  }

  private buildFairnessScores(
    workers: WorkerCandidate[],
    recentMainSchedules: ScheduleLike[],
  ) {
    const scores = new Map<string, FairnessScore>();

    workers.forEach((worker) => {
      scores.set(this.toId(worker._id), {
        count: 0,
        lastAssignedTime: 0,
      });
    });

    recentMainSchedules.forEach((schedule) => {
      const assignedTime = this.toDate(schedule.date).getTime();
      schedule.assignments?.forEach((assignment) => {
        if (!assignment.worker_id) {
          return;
        }

        const workerId = this.toId(assignment.worker_id);
        const score = scores.get(workerId) ?? {
          count: 0,
          lastAssignedTime: 0,
        };

        scores.set(workerId, {
          count: score.count + 1,
          lastAssignedTime: Math.max(score.lastAssignedTime, assignedTime),
        });
      });
    });

    return scores;
  }

  private incrementFairnessScore(
    scores: Map<string, FairnessScore>,
    workerId: string,
    date: Date,
  ) {
    const score = scores.get(workerId) ?? {
      count: 0,
      lastAssignedTime: 0,
    };

    scores.set(workerId, {
      count: score.count + 1,
      lastAssignedTime: Math.max(score.lastAssignedTime, date.getTime()),
    });
  }

  private getAssignedWorkerIds(schedules: ScheduleLike[]) {
    const workerIds = new Set<string>();

    schedules.forEach((schedule) => {
      schedule.assignments?.forEach((assignment) => {
        if (assignment.worker_id) {
          workerIds.add(this.toId(assignment.worker_id));
        }
      });
    });

    return workerIds;
  }

  private groupSchedulesByDate(schedules: ScheduleLike[]) {
    return schedules.reduce<Map<string, ScheduleLike[]>>((acc, schedule) => {
      const dateKey = this.toDateKey(schedule.date);
      const schedulesOnDate = acc.get(dateKey) ?? [];
      schedulesOnDate.push(schedule);
      acc.set(dateKey, schedulesOnDate);

      return acc;
    }, new Map());
  }

  private getSundaysInMonth(year: number, month: number) {
    const dates: Date[] = [];
    const current = new Date(Date.UTC(year, month - 1, 1));

    while (current.getUTCMonth() === month - 1) {
      if (current.getUTCDay() === 0) {
        dates.push(new Date(current));
      }

      current.setUTCDate(current.getUTCDate() + 1);
    }

    return dates;
  }

  private getWorkerLabel(worker: WorkerCandidate) {
    return worker.label ?? WorkerLabel.Main;
  }

  private toDate(value: Date | string) {
    return value instanceof Date ? value : new Date(value);
  }

  private toDateKey(value: Date | string) {
    return this.toDate(value).toISOString().slice(0, 10);
  }

  private toId(value: unknown) {
    if (typeof value === 'string') {
      return value;
    }

    if (value && typeof (value as { toString: () => string }).toString === 'function') {
      return (value as { toString: () => string }).toString();
    }

    return String(value);
  }
}
