import {
  BadRequestException,
  Injectable,
  NotFoundException,
} from '@nestjs/common';
import { Cron } from '@nestjs/schedule';
import { Types } from 'mongoose';
import { ScheduleStatus } from 'src/common/enums/schedule-status.enum';
import { ServiceType } from 'src/common/enums/service-type.enum';
import { WorkerRole } from 'src/common/enums/worker-role.enum';
import { WorkerStatus } from 'src/common/enums/worker-status.enum';
import { WorkersService } from 'src/workers/workers.service';
import { AutoGenerationConfirmDto } from './dto/auto-generation-confirm.dto';
import { AutoGenerationPreviewDto } from './dto/auto-generation-preview.dto';
import { CreateScheduleDTO } from './dto/create-schedule.dto';
import { ScheduleAssignmentDto } from './dto/schedule-assignment.dto';
import { UpdateScheduleDto } from './dto/update-schedule.dto';
import { ScheduleAutoGenerationService } from './schedule-auto-generation.service';
import { SchedulesRepository } from './repositories/schedules.repository';

@Injectable()
export class SchedulesService {
  private readonly mainRequiredRoles = [
    WorkerRole.Leader,
    WorkerRole.Acoustic,
    WorkerRole.Bass,
    WorkerRole.Drums,
  ];

  private readonly nonMainRequiredRoles = [
    WorkerRole.Leader,
    WorkerRole.Acoustic,
  ];

  private readonly nonMainAllowedRoles = new Set([
    WorkerRole.Leader,
    WorkerRole.Acoustic,
    WorkerRole.Bass,
    WorkerRole.Drums,
    WorkerRole.Beatbox,
  ]);

  constructor(
    private readonly schedulesRepository: SchedulesRepository,
    private readonly workersService: WorkersService,
    private readonly scheduleAutoGenerationService: ScheduleAutoGenerationService,
  ) {}

  async getAllSchedules(query: any = {}) {
    const filter: any = {};

    if (query.status) {
      filter.status = query.status;
    }

    if (query.service_type) {
      filter.service_type = query.service_type;
    }

    return await this.schedulesRepository.getRecords(filter, 1, 100, 'asc', 'date');
  }

  async getMyAssignments(userId: string) {
    const worker = await this.workersService.findWorkerByUserId(userId);

    if (!worker) {
      return { worker: null, items: [] };
    }

    const items = await this.schedulesRepository.findWorkerAssignments(
      worker._id.toString(),
      this.getCurrentLocalDate(),
    );

    return {
      worker: {
        _id: worker._id,
        name: worker.name,
      },
      items,
    };
  }

  async getScheduleById(id: string) {
    const schedule = await this.schedulesRepository.getRecordById(id);

    if (!schedule) {
      throw new NotFoundException('Schedule not found');
    }

    return schedule;
  }

  async createSchedule(dto: CreateScheduleDTO) {
    const date = this.normalizeScheduleDate(dto.date);
    const serviceType = dto.service_type || ServiceType.Main;
    const assignments = await this.validateAndBuildAssignments(
      dto.assignments,
      date,
      serviceType,
    );

    return await this.schedulesRepository.insertRecord({
      date,
      service_type: serviceType,
      status: dto.status || this.getStatusForDate(date),
      assignments,
      songs: dto.songs || [],
      lineup: dto.lineup,
      notes: dto.notes,
    } as any);
  }

  async previewAutoGeneratedSchedules(dto: AutoGenerationPreviewDto) {
    return await this.scheduleAutoGenerationService.preview(dto);
  }

  async confirmAutoGeneratedSchedules(dto: AutoGenerationConfirmDto) {
    const seenDates = new Set<string>();
    const seenWorkerIdsByDate = new Map<string, Set<string>>();
    const preparedSchedules: any[] = [];

    for (const schedule of dto.schedules) {
      const date = this.normalizeScheduleDate(schedule.date);
      const dateKey = date.toISOString().slice(0, 10);
      const serviceType = schedule.service_type || ServiceType.Main;
      const scheduleKey = `${dateKey}:${serviceType}`;

      if (!this.scheduleAutoGenerationService.isGenerationDate(serviceType, date)) {
        throw new BadRequestException(
          `${dateKey} is not a valid auto-generation date for ${serviceType}`,
        );
      }

      if (seenDates.has(scheduleKey)) {
        throw new BadRequestException(
          `Duplicate generated ${serviceType} schedule date: ${dateKey}`,
        );
      }

      seenDates.add(scheduleKey);

      const existingSchedule = await this.schedulesRepository.findScheduleOnDate(
        date,
        serviceType,
      );

      if (existingSchedule) {
        throw new BadRequestException(
          `A ${serviceType} service schedule already exists for ${dateKey}`,
        );
      }

      const assignments = await this.validateAndBuildAssignments(
        schedule.assignments,
        date,
        serviceType,
      );
      const seenWorkerIds = seenWorkerIdsByDate.get(dateKey) ?? new Set<string>();
      const conflictingWorker = assignments.find((assignment) => {
        return seenWorkerIds.has(assignment.worker_id.toString());
      });

      if (conflictingWorker) {
        throw new BadRequestException(
          'A worker is already assigned to another generated schedule on this date',
        );
      }

      assignments.forEach((assignment) => {
        seenWorkerIds.add(assignment.worker_id.toString());
      });
      seenWorkerIdsByDate.set(dateKey, seenWorkerIds);

      preparedSchedules.push({
        date,
        service_type: serviceType,
        status: this.getStatusForDate(date),
        assignments,
        songs: schedule.songs || [],
        lineup: schedule.lineup,
        notes: schedule.notes,
      });
    }

    const createdSchedules: any[] = [];

    for (const schedule of preparedSchedules) {
      createdSchedules.push(
        await this.schedulesRepository.insertRecord(schedule as any),
      );
    }

    return createdSchedules;
  }

  async updateScheduleById(id: string, dto: UpdateScheduleDto) {
    const existing = await this.getScheduleById(id);
    const date = dto.date ? this.normalizeScheduleDate(dto.date) : existing.date;
    const serviceType = dto.service_type || existing.service_type || ServiceType.Main;
    const update: any = { ...dto, date };

    if (dto.assignments) {
      update.assignments = await this.validateAndBuildAssignments(
        dto.assignments,
        date,
        serviceType,
        id,
      );
    } else if (dto.service_type) {
      this.validateServiceStructure(existing.assignments as any, serviceType);
    }

    const schedule = await this.schedulesRepository.updateRecord(
      { _id: id } as any,
      update,
    );

    if (!schedule) {
      throw new NotFoundException('Schedule not found');
    }

    return schedule;
  }

  async deleteScheduleById(id: string) {
    const result = await this.schedulesRepository.deleteRecord({ _id: id } as any);

    if (!result.deletedCount) {
      throw new NotFoundException('Schedule not found');
    }

    return result;
  }

  @Cron('0 0 * * 1', {
    timeZone: process.env.CHURCH_TIMEZONE || 'Asia/Singapore',
  })
  async syncPastScheduleStatuses() {
    const throughDate = this.getLastCompletedLocalDate(new Date());

    if (!throughDate) {
      return { modifiedCount: 0 };
    }

    return await this.schedulesRepository.markSchedulesInactiveThroughDate(
      throughDate,
    );
  }

  private async validateAndBuildAssignments(
    assignments: ScheduleAssignmentDto[],
    date: Date,
    serviceType: ServiceType,
    excludeScheduleId?: string,
  ) {
    if (!assignments?.length) {
      throw new BadRequestException('At least one assignment is required');
    }

    this.validateServiceStructure(assignments, serviceType);
    this.validateNoDuplicateWorkers(assignments);

    const workerIds = assignments.map(
      (assignment) => new Types.ObjectId(assignment.worker_id),
    );
    const conflict = await this.schedulesRepository.findWorkerConflictOnDate(
      date,
      workerIds,
      excludeScheduleId,
    );

    if (conflict) {
      throw new BadRequestException(
        'A worker is already assigned to another schedule on this date',
      );
    }

    return await Promise.all(
      assignments.map(async (assignment) => {
        const worker = await this.workersService.getWorkerById(
          assignment.worker_id,
        );

        if (worker.status !== WorkerStatus.Active) {
          throw new BadRequestException('Inactive workers cannot be assigned');
        }

        if (!worker.roles?.includes(assignment.role)) {
          throw new BadRequestException(
            `${worker.name} cannot be assigned to ${assignment.role}`,
          );
        }

        return {
          role: assignment.role,
          worker_id: new Types.ObjectId(assignment.worker_id),
          worker_name: worker.name,
        };
      }),
    );
  }

  private validateServiceStructure(
    assignments: Pick<ScheduleAssignmentDto, 'role'>[],
    serviceType: ServiceType,
  ) {
    if (serviceType !== ServiceType.Main) {
      const unsupportedRoles = assignments
        .map((assignment) => assignment.role)
        .filter((role) => {
          return !(
            this.nonMainAllowedRoles.has(role) ||
            (serviceType === ServiceType.Midweek && role === WorkerRole.Keyboard)
          );
        });

      if (unsupportedRoles.length) {
        throw new BadRequestException(
          `Non-main schedules only support Leader, Acoustic, Bass, and Drums/Beatbox assignments; Midweek also supports Keyboard`,
        );
      }
    }

    const assignedRoles = new Set(assignments.map((assignment) => assignment.role));
    const missingRoles = this.getRequiredRoles(serviceType).filter(
      (role) => !assignedRoles.has(role),
    );

    if (missingRoles.length) {
      throw new BadRequestException(
        `Missing required roles: ${missingRoles.join(', ')}`,
      );
    }

    if (serviceType !== ServiceType.Main) {
      const percussionAssignments = assignments.filter(
        ({ role }) => role === WorkerRole.Drums || role === WorkerRole.Beatbox,
      );
      const instrumentAssignments = assignments.filter(({ role }) => {
        return (
          role === WorkerRole.Acoustic ||
          (serviceType === ServiceType.Midweek && role === WorkerRole.Keyboard)
        );
      });

      const roleCounts = assignments.reduce<Map<WorkerRole, number>>(
        (counts, { role }) => counts.set(role, (counts.get(role) || 0) + 1),
        new Map(),
      );

      if (
        roleCounts.get(WorkerRole.Leader) !== 1 ||
        instrumentAssignments.length !== 1 ||
        (roleCounts.get(WorkerRole.Bass) || 0) > 1 ||
        percussionAssignments.length > 1
      ) {
        throw new BadRequestException(
          serviceType === ServiceType.Midweek
            ? 'Midweek schedules require one Leader and one Acoustic/Keyboard assignment, with optional Bass and Drums/Beatbox assignments'
            : 'Non-main schedules require one Leader and one Acoustic, with optional Bass and Drums/Beatbox assignments',
        );
      }
    }
  }

  private getRequiredRoles(serviceType: ServiceType) {
    if (serviceType === ServiceType.Main) {
      return this.mainRequiredRoles;
    }

    return serviceType === ServiceType.Midweek
      ? [WorkerRole.Leader]
      : this.nonMainRequiredRoles;
  }

  private validateNoDuplicateWorkers(assignments: ScheduleAssignmentDto[]) {
    const rolesByWorker = assignments.reduce<Map<string, WorkerRole[]>>(
      (roles, assignment) => {
        const workerRoles = roles.get(assignment.worker_id) ?? [];
        workerRoles.push(assignment.role);
        roles.set(assignment.worker_id, workerRoles);
        return roles;
      },
      new Map(),
    );
    const hasUnsupportedDuplicate = [...rolesByWorker.values()].some((roles) => {
      if (roles.length === 1) {
        return false;
      }

      const roleSet = new Set(roles);
      return !(
        roles.length === 2 &&
        roleSet.has(WorkerRole.Acoustic) &&
        (roleSet.has(WorkerRole.Leader) || roleSet.has(WorkerRole.Backup))
      );
    });

    if (hasUnsupportedDuplicate) {
      throw new BadRequestException(
        'A worker cannot be assigned to multiple roles in the same schedule, except Leader/Acoustic or Backup/Acoustic',
      );
    }
  }

  private normalizeScheduleDate(value: string | Date) {
    const date = new Date(value);

    if (Number.isNaN(date.getTime())) {
      throw new BadRequestException('Invalid schedule date');
    }

    date.setUTCHours(0, 0, 0, 0);

    return date;
  }

  private getStatusForDate(date: Date) {
    const throughDate = this.getLastCompletedLocalDate(new Date());

    if (throughDate && date <= throughDate) {
      return ScheduleStatus.Inactive;
    }

    return ScheduleStatus.Active;
  }

  private getLastCompletedLocalDate(now: Date) {
    const offsetMinutes = Number(process.env.CHURCH_TIMEZONE_OFFSET_MINUTES || 480);
    const localNow = new Date(now.getTime() + offsetMinutes * 60 * 1000);

    if (localNow.getUTCDay() === 0) {
      return null;
    }

    const completedLocalDate = new Date(
      Date.UTC(
        localNow.getUTCFullYear(),
        localNow.getUTCMonth(),
        localNow.getUTCDate(),
      ),
    );

    completedLocalDate.setUTCDate(completedLocalDate.getUTCDate() - 1);

    return completedLocalDate;
  }

  private getCurrentLocalDate() {
    const offsetMinutes = Number(process.env.CHURCH_TIMEZONE_OFFSET_MINUTES || 480);
    const localNow = new Date(Date.now() + offsetMinutes * 60 * 1000);

    return new Date(Date.UTC(
      localNow.getUTCFullYear(),
      localNow.getUTCMonth(),
      localNow.getUTCDate(),
    ));
  }
}
